### ISSUE TITLE
Implimentation with xscreensaver

### ISSUE THREAD

**Issue by SdeGeata** [nischi/MMM-MotionControl#3]
Hello again Nischi!

   I am currently using xscreensaver on my raspi. My goal is to use your Motion Control module in conjunction with xscreensaver. Ideally, xscreensaver would start after a couple of minutes, then your module would turn off the display after about 5 more.

I was wondering how i could get your module to deactivate xscreensaver upon motion detection?

**Comment by nischi** [comment]
Hi @SdeGeata 

So you wanna disable xscreensaver if a motion is detected, right? I think that should be a seperate module then, because this module is only a hub for detecting motions. So i only send notifications if a motion is detected, and send another one if no motion is active anymore. 

The other module should get the notifications and deactivate the xscreensaver if nessesary, like my https://github.com/nischi/MMM-CECControl module do with the tv.

**Comment by SdeGeata** [comment]
Would there be a way to piggy-back `os.system("xscreensaver-command -deactivate")` somewhere in your MotionControl module or CECControl module - I have both installed? I would rather be able to do so with existing modules and existing camera, I don't really want to add another sensor just to turn off the screensaver and I have no idea how to write a module.

**Comment by nischi** [comment]
Yes we can deactivate the Screensaver in CECControl. I will create an Issue on that Project and will implement it in the next few days. Or you are free to send me a Pull-Request :)
